### ISSUE TITLE
same package

### ISSUE THREAD

**Issue by hadilo** [xujiaji/MVPCreator#1]
can you make contract, view, presenter, model, activity/fragment are placed in the same package like https://github.com/googlesamples/android-architecture/tree/todo-mvp/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/taskdetail

**Comment by xujiaji** [comment]
Thank you, this is very good, the next version to be put a package of choice.

**Comment by hadilo** [comment]
thanks for respond my suggest. i will wait next update.

**Comment by xujiaji** [comment]
According to your suggestion, if you have time to hope that you can experience it, MVPManager can now create all the files in a package. I will be officially released in a few days, the following has a temporary download link.

[Download MVPManager.zip](https://github.com/xujiaji/MVPManager/files/1367822/MVPManager.zip)

![image](https://user-images.githubusercontent.com/16447251/31329232-b16079b4-ad0b-11e7-853b-1de3f071c021.png)

**Comment by liguangze** [comment]
棒棒的

**Comment by xujiaji** [comment]
Updated 2.0.0
